[versions]
compileSdk = "35"
minSdk = "26"
targetSdk = "34"
agp = "8.7.2"
kotlin = "2.0.21"
[libraries]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }